---

- name: Converge for Centos
  hosts: coturn_centos
  pre_tasks:
    - name: install firewalld
      ansible.builtin.dnf:
        name: firewalld
    - name: enable firewalld
      ansible.builtin.service:
        name: firewalld
        enabled: true
        state: started
  roles:
    - role: elan.bbb_coturn
      configure_for_firewalld: true
      listening_ip: 127.0.0.1

- name: Converge for Ubuntu
  hosts: coturn_ubuntu
  pre_tasks:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: true
  roles:
    - role: elan.bbb_coturn
      listening_ip: 127.0.0.1
