---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: coturn_centos
    image: quay.io/centos/centos:stream8
    pre_build_image: false
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: coturn_ubuntu
    image: docker.io/ubuntu:latest
    pre_build_image: false
    privileged: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
lint: |
  ansible-lint
  yamllint -c .yamllint .
provisioner:
  name: ansible
  inventory:
    host_vars:
      centos:
        ansible_user: ansible
